/** Curated service hosts, not fuzzy item-name matches or a site trust list.
 * Never add shared hosting suffixes such as github.io, vercel.app or netlify.app:
 * those sites belong to users, not to the provider represented by the logo.
 * More-specific entries (mail.google.com) take precedence over parent domains.
 */
export const SERVICE_BRANDS = [
  { id: 'github', domains: ['github.com'] },
  { id: 'gitlab', domains: ['gitlab.com'] },
  { id: 'gitea', domains: ['gitea.com'] },
  { id: 'codeberg', domains: ['codeberg.org'] },
  { id: 'bitbucket', domains: ['bitbucket.org'] },
  { id: 'google', domains: ['google.com'] },
  { id: 'gmail', domains: ['gmail.com', 'mail.google.com'] },
  { id: 'apple', domains: ['apple.com', 'icloud.com'] },
  { id: 'claude', domains: ['claude.ai'] },
  { id: 'anthropic', domains: ['anthropic.com'] },
  { id: 'deepseek', domains: ['deepseek.com'], keywords: ['深度求索', '中国网站'] },
  { id: 'bilibili', domains: ['bilibili.com'], keywords: ['哔哩哔哩', 'B站', '中国网站'] },
  { id: 'qq', domains: ['qq.com'], keywords: ['腾讯', 'QQ', '中国网站'] },
  { id: 'wechat', domains: ['wechat.com', 'weixin.qq.com'], keywords: ['微信', '中国网站'] },
  { id: 'baidu', domains: ['baidu.com'], keywords: ['百度', '中国网站'] },
  { id: 'zhihu', domains: ['zhihu.com'], keywords: ['知乎', '中国网站'] },
  { id: 'v2ex', domains: ['v2ex.com'], keywords: ['中国网站'] },
  { id: 'xiaomi', domains: ['mi.com', 'xiaomi.com'], keywords: ['小米', '中国网站'] },
  { id: 'huawei', domains: ['huawei.com'], keywords: ['华为', '中国网站'] },
  { id: 'steam', domains: ['steampowered.com', 'steamcommunity.com'] },
  { id: 'discord', domains: ['discord.com', 'discordapp.com'] },
  { id: 'telegram', domains: ['telegram.org'] },
  { id: 'signal', domains: ['signal.org'] },
  { id: 'notion', domains: ['notion.so', 'notion.com'] },
  { id: 'figma', domains: ['figma.com'] },
  { id: 'linear', domains: ['linear.app'] },
  { id: 'obsidian', domains: ['obsidian.md'] },
  { id: 'dropbox', domains: ['dropbox.com'] },
  { id: 'proton', domains: ['proton.me'] },
  { id: 'protonmail', domains: ['protonmail.com', 'mail.proton.me'] },
  { id: 'mega', domains: ['mega.nz', 'mega.io'] },
  { id: 'cloudflare', domains: ['cloudflare.com'] },
  { id: 'vercel', domains: ['vercel.com'] },
  { id: 'netlify', domains: ['netlify.com'] },
  { id: 'digitalocean', domains: ['digitalocean.com'] },
  { id: 'hetzner', domains: ['hetzner.com', 'hetzner.cloud'] },
  { id: 'docker', domains: ['docker.com'] },
  { id: 'npm', domains: ['npmjs.com'] },
  { id: 'pypi', domains: ['pypi.org'] },
  { id: 'tailscale', domains: ['tailscale.com'] },
  { id: 'reddit', domains: ['reddit.com'] },
  { id: 'youtube', domains: ['youtube.com'] },
  { id: 'spotify', domains: ['spotify.com'] },
  { id: 'netflix', domains: ['netflix.com'] },
  { id: 'twitch', domains: ['twitch.tv'] },
  { id: 'x', domains: ['x.com', 'twitter.com'] },
  { id: 'facebook', domains: ['facebook.com'] },
  { id: 'instagram', domains: ['instagram.com'] },
  // Chinese services. Keywords are catalogue search aids, NEVER matching rules.
  { id: 'taobao', domains: ['taobao.com'], keywords: ['淘宝', 'Taobao', '中国网站'] },
  { id: 'jd', domains: ['jd.com'], keywords: ['京东', 'JD', '中国网站'] },
  { id: 'pinduoduo', domains: ['pinduoduo.com'], keywords: ['拼多多', 'Pinduoduo', '中国网站'] },
  { id: 'alipay', domains: ['alipay.com'], keywords: ['支付宝', 'Alipay', '中国网站'] },
  { id: 'weibo', domains: ['weibo.com'], keywords: ['微博', 'Weibo', '中国网站'] },
  { id: 'xiaohongshu', domains: ['xiaohongshu.com'], keywords: ['小红书', 'Xiaohongshu', 'RedNote', '中国网站'] },
  { id: 'douyin', domains: ['douyin.com'], keywords: ['抖音', 'Douyin', '中国网站'] },
  { id: 'kuaishou', domains: ['kuaishou.com'], keywords: ['快手', 'Kuaishou', '中国网站'] },
  { id: 'neteasemail', domains: ['mail.163.com', 'mail.126.com', 'email.163.com', 'email.126.com'], keywords: ['网易邮箱', 'NetEase', '163', '126', '中国网站'] },
  { id: 'aliyun', domains: ['aliyun.com', 'alibabacloud.com'], keywords: ['阿里云', 'Aliyun', 'Alibaba Cloud', '中国网站'] },
  { id: 'tencentcloud', domains: ['cloud.tencent.com'], keywords: ['腾讯云', 'Tencent Cloud', '中国网站'] },
  { id: 'gitee', domains: ['gitee.com'], keywords: ['码云', 'Gitee', '中国网站'] },
  { id: 'yuque', domains: ['yuque.com'], keywords: ['语雀', 'Yuque', '中国网站'] },
  { id: 'douban', domains: ['douban.com'], keywords: ['豆瓣', 'Douban', '中国网站'] },
  { id: 'dingtalk', domains: ['dingtalk.com'], keywords: ['钉钉', 'DingTalk', '中国网站'] },
  { id: 'feishu', domains: ['feishu.cn'], keywords: ['飞书', 'Feishu', '中国网站'] },
  // Exchange/DEX marks identify saved sites; they are not endorsements or trust badges.
  { id: 'binance', domains: ['binance.com'], keywords: ['币安', 'Binance', 'Web3', '交易所'] },
  { id: 'okx', domains: ['okx.com'], keywords: ['欧易', 'OKX', 'Web3', '交易所'] },
  { id: 'coinbase', domains: ['coinbase.com'], keywords: ['Coinbase', 'Web3', '交易所'] },
  { id: 'kraken', domains: ['kraken.com'], keywords: ['Kraken', 'Web3', '交易所'] },
  { id: 'bitget', domains: ['bitget.com'], keywords: ['Bitget', 'Web3', '交易所'] },
  { id: 'gate', domains: ['gate.com', 'gate.io'], keywords: ['Gate', '大门', '芝麻开门', 'Web3', '交易所'] },
  { id: 'kucoin', domains: ['kucoin.com'], keywords: ['KuCoin', '库币', 'Web3', '交易所'] },
  { id: 'htx', domains: ['htx.com'], keywords: ['HTX', '火币', 'Huobi', 'Web3', '交易所'] },
  { id: 'mexc', domains: ['mexc.com'], keywords: ['MEXC', '抹茶', 'Web3', '交易所'] },
  { id: 'cryptodotcom', domains: ['crypto.com'], keywords: ['Crypto.com', 'Web3', '交易所'] },
  { id: 'bitfinex', domains: ['bitfinex.com'], keywords: ['Bitfinex', 'Web3', '交易所'] },
  { id: 'uniswap', domains: ['uniswap.org'], keywords: ['Uniswap', 'Web3', 'DEX', '去中心化交易所'] },
  { id: 'pancakeswap', domains: ['pancakeswap.finance'], keywords: ['PancakeSwap', '薄饼', 'Web3', 'DEX', '去中心化交易所'] },
  { id: 'dydx', domains: ['dydx.trade', 'dydx.exchange'], keywords: ['dYdX', 'Web3', 'DEX', '去中心化交易所'] },
] as const;
