// Generated by bun run build:service-icons; unmodified official site artwork.
import google from './google.png';
import taobao from './assets/taobao.ico';
import jd from './assets/jd.ico';
import pinduoduo from './assets/pinduoduo.png';
import alipay from './assets/alipay.ico';
import weibo from './assets/weibo.ico';
import xiaohongshu from './assets/xiaohongshu.png';
import douyin from './assets/douyin.ico';
import kuaishou from './assets/kuaishou.ico';
import neteasemail from './assets/neteasemail.png';
import aliyun from './assets/aliyun.png';
import tencentcloud from './assets/tencentcloud.ico';
import gitee from './assets/gitee.ico';
import yuque from './assets/yuque.png';
import douban from './assets/douban.ico';
import dingtalk from './assets/dingtalk.png';
import feishu from './assets/feishu.png';
import binance from './assets/binance.png';
import okx from './assets/okx.png';
import coinbase from './assets/coinbase.png';
import kraken from './assets/kraken.png';
import bitget from './assets/bitget.png';
import gate from './assets/gate.ico';
import kucoin from './assets/kucoin.png';
import htx from './assets/htx.png';
import mexc from './assets/mexc.webp';
import cryptodotcom from './assets/cryptodotcom.ico';
import bitfinex from './assets/bitfinex.ico';
import uniswap from './assets/uniswap.png';
import pancakeswap from './assets/pancakeswap.png';
import dydx from './assets/dydx.svg';
export const LOCAL_ASSETS: Readonly<Partial<Record<string, string>>> = {
  google,
  taobao,
  jd,
  pinduoduo,
  alipay,
  weibo,
  xiaohongshu,
  douyin,
  kuaishou,
  neteasemail,
  aliyun,
  tencentcloud,
  gitee,
  yuque,
  douban,
  dingtalk,
  feishu,
  binance,
  okx,
  coinbase,
  kraken,
  bitget,
  gate,
  kucoin,
  htx,
  mexc,
  cryptodotcom,
  bitfinex,
  uniswap,
  pancakeswap,
  dydx,
};
